# Generated by Django 5.0.7 on 2026-06-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_num', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('area_type', models.CharField(choices=[('police', 'Police District'), ('community', 'Community Area')], max_length=20)),
                ('population', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['district_num'],
            },
        ),
        migrations.CreateModel(
            name='OffenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('violent', 'Violent'), ('property', 'Property'), ('quality_of_life', 'Quality of Life')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Offense categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField()),
                ('block', models.CharField(max_length=200)),
                ('arrest', models.BooleanField(default=False)),
                ('domestic', models.BooleanField(default=False)),
                ('fbi_code', models.CharField(max_length=10)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='crime_api.district')),
                ('primary_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='crime_api.offensecategory')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
